import { typographyCss } from './typography-generated.js';

export { typographyCss };

// Layout, task-list, and print styles only.
// Typography (headings, prose, code, tables, etc.) is generated by
// @tailwindcss/typography at build time — see typographyCss above.
export const baseCss = `
:root {
  color-scheme: light dark;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: #ffffff;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}
@media (prefers-color-scheme: dark) {
  body {
    background: #0d1117;
  }
}
main.markdown-body {
  max-width: 48rem;
  margin: 0 auto;
  padding: 3rem 1.5rem 6rem;
}
.task-list-item { list-style: none; }
.task-list-item input { margin: 0 0.4em 0 -1.4em; }
@media print {
  main.markdown-body { max-width: none; padding: 0; }
  a { color: inherit; }
  pre, blockquote, table, img { break-inside: avoid; }
  h1, h2, h3, h4, h5, h6 { break-after: avoid; }
}
`;
